[default.general]
chip = "stm32f303re"
log_level = "WARN"

[rtt.rtt]
# Whether or not an RTTUI should be opened after flashing.
# This is exclusive and cannot be used with GDB at the moment.
enabled = true
# A list of channel associations to be displayed. If left empty, all channels are displayed.
# formats are: String, Defmt, BinaryLE,
channels = [
    # { up = 0, down = 0, name = "name", format = "String" },

    # How to enable Defmt formatting (https://github.com/knurling-rs/defmt)
    # (formats on host, not on microcontroller)?
    # microcontroller setup: https://github.com/knurling-rs/app-template
    # { up = 0, name = "defmt_name", format = "Defmt" },
]
# The duration in ms for which the logger should retry to attach to RTT.
timeout = 3000
# Whether timestamps in the RTTUI are enabled
show_timestamps = true
# Whether to save rtt history buffer on exit.
log_enabled = false
# Where to save rtt history buffer relative to manifest path.
log_path = "./logs"

[gdb.gdb]
# Whether or not a GDB server should be opened after flashing.
# This is exclusive and cannot be used with RTT at the moment.
enabled = true
# The connection string in host:port format wher the GDB server will open a socket.
gdb_connection_string = "127.0.0.1:1337"